version: '3.8'
services:
    php:
        build:
            context: .
            target: php
            dockerfile: docker/Dockerfile
            args:
                uid: ${WWWUSER}
        container_name: bolt-cms-site
        environment:
            - APACHE_RUN_USER=#${WWWUSER}
            - APACHE_RUN_GROUP=#${WWWGROUP}
        expose:
            - "80"
            - "5173"
        networks:
            - internal
            - proxy
        volumes:
            - ./bolt-project:/var/www/html:rw
        restart: always

networks:
    internal:
        name: bolt-net
        driver: bridge
    proxy:
        name: proxy-net-external
        external: true
